### Create a cart
POST http://localhost:3000/carts
Content-Type: application/json

{}

### Add 3 coffees to cart 1
POST http://localhost:3000/carts/1/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 3
}

### Add 4 coffees to cart 3
POST http://localhost:3000/carts/3/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 4
}

### Add 8 coffees to cart 4
POST http://localhost:3000/carts/4/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 8
}

### Add 3 coffees and 2 teas to cart 5
POST http://localhost:3000/carts/5/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 3
}

### Add 2 teas to cart 5
POST http://localhost:3000/carts/5/items
Content-Type: application/json

{
  "productId": 2,
  "quantity": 2
}

### Add 3 coffees to cart 6
POST http://localhost:3000/carts/6/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 3
}

### Add 3 cakes to cart 6
POST http://localhost:3000/carts/6/items
Content-Type: application/json

{
  "productId": 3,
  "quantity": 3
}

### Testing validation for adding items to cart
### Add 0 coffees to cart 1
POST http://localhost:3000/carts/1/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 0
}

### Get cart 1 (which has 3 coffees)
GET http://localhost:3000/carts/1

### Get cart 2 (which is empty)
GET http://localhost:3000/carts/2

### Get cart 999 (which does not exist)
GET http://localhost:3000/carts/999

### Calculate the total price of cart 1 (3 coffees - should not apply any discount)
POST  http://localhost:3000/carts/1/price
Content-Type: application/json

{}

### Calculate the total price of cart 3 (4 coffees - should apply buy 3 get 1 free discount)
POST  http://localhost:3000/carts/3/price
Content-Type: application/json

{}

### Calculate the total price of cart 4 (8 coffees - should apply buy 3 get 1 free discount twice and also apply £20 threshold discount)
POST  http://localhost:3000/carts/4/price
Content-Type: application/json

{}

### Calculate the total price of cart 5 (3 coffees and 2 teas)
POST  http://localhost:3000/carts/5/price
Content-Type: application/json

{}

### Calculate the total price of cart 6 (3 coffees and 3 cakes - should apply £20 threshold discount)
POST  http://localhost:3000/carts/6/price
Content-Type: application/json

{}

### Calculate price of cart 1 with coupon code "WELCOME5" (3 coffees - should apply £5 discount)
POST http://localhost:3000/carts/1/price
Content-Type: application/json

{
  "couponCode": "WELCOME5"
}

### Tests cart 1 with an invalid coupon code "INVALIDCODE" (3 coffees - should not apply any discount)
POST http://localhost:3000/carts/1/price
Content-Type: application/json

{
  "couponCode": "INVALIDCODE"
}

### Calculate price of cart 3 with coupon code "WELCOME5" (4 coffees - should apply buy 3 get 1 free discount and £5 discount)
POST http://localhost:3000/carts/3/price
Content-Type: application/json

{
  "couponCode": "WELCOME5"
}

### Calculate price of cart 4 with coupon code "WELCOME5" (8 coffees - should apply buy 3 get 1 free discount twice, £20 threshold discount and £5 discount)
POST http://localhost:3000/carts/4/price
Content-Type: application/json

{
  "couponCode": "WELCOME5"
}


### Testing frontend before frontend is fully implemented
### Get cart 7 (should have 1 coffee and 1 tea)
GET http://localhost:3000/carts/7

###
GET http://localhost:3000/carts/8

###
GET http://localhost:3000/carts/9