### Create a cart
POST http://localhost:3000/carts
Content-Type: application/json

{}

### Add 3 coffees to cart 1
POST http://localhost:3000/carts/1/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 3
}

### Add 4 coffees to cart 3
POST http://localhost:3000/carts/3/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 4
}

### Add 8 coffees to cart 4
POST http://localhost:3000/carts/4/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 8
}

### Testing validation for adding items to cart
### Add 0 coffees to cart 1
POST http://localhost:3000/carts/1/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 0
}

### Get cart 1
GET http://localhost:3000/carts/1

### Get cart 2 (which is empty)
GET http://localhost:3000/carts/2

### Get cart 999 (which does not exist)
GET http://localhost:3000/carts/999

### Calculate the total price of cart 1
GET http://localhost:3000/carts/1/price

### Calculate the total price of cart 3
GET http://localhost:3000/carts/3/price

### Calculate the total price of cart 4
GET http://localhost:3000/carts/4/price